# Generated by Django 5.1.4 on 2025-02-09 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_qr_code', '0010_qrcodes_logo_alter_qrcodes_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcodes',
            name='logo',
        ),
    ]
