# Generated by Django 5.1.4 on 2025-02-27 04:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_qr_code', '0012_qrcodes_desktop_alter_qrcodes_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodes',
            name='url',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AlterField(
            model_name='qrcodes',
            name='date',
            field=models.DateField(default=datetime.date(2025, 2, 27)),
        ),
    ]
