# Generated by Django 5.1.4 on 2025-03-06 13:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_qr_code', '0013_qrcodes_url_alter_qrcodes_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodes',
            name='workable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='qrcodes',
            name='date',
            field=models.DateField(default=datetime.date(2025, 3, 6)),
        ),
    ]
