# Generated by Django 5.1.4 on 2025-03-07 05:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_qr_code', '0014_qrcodes_workable_alter_qrcodes_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcodes',
            name='date',
            field=models.DateField(default=datetime.date(2025, 3, 7)),
        ),
    ]
