# Generated by Django 5.1.4 on 2025-01-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_qr_code', '0002_qrcodes_image_alter_qrcodes_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcodes',
            name='image',
            field=models.TextField(default='none'),
        ),
    ]
