# Generated by Django 5.1.4 on 2025-02-02 11:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_qr_code', '0003_alter_qrcodes_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodes',
            name='date',
            field=models.DateField(default=datetime.date(2025, 2, 2)),
        ),
    ]
