# Generated by Django 5.1.4 on 2025-02-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_qr_code', '0004_qrcodes_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcodes',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
