# Generated by Django 5.1.4 on 2025-02-06 14:11

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_qr_code', '0007_alter_qrcodes_user'),
        ('registration', '0005_rename_subsribe_profile_subscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcodes',
            name='date',
            field=models.DateField(default=datetime.date(2025, 2, 6)),
        ),
        migrations.AlterField(
            model_name='qrcodes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.profile'),
        ),
    ]
