# Generated by Django 5.1.4 on 2025-01-23 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_users_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
