# Generated by Django 5.1.4 on 2025-02-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_rename_subsribe_profile_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='desktop',
            field=models.BooleanField(default=False),
        ),
    ]
