# Generated by Django 5.1.4 on 2025-03-07 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_profile_desktop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='desktop',
            field=models.IntegerField(max_length=1000),
        ),
    ]
