# Generated by Django 5.1.4 on 2025-02-05 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        ('registration', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomcodes',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registration.profile'),
        ),
    ]
